name: Build for Linux
on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Set env
      run: if grep -Fxq "devel" cmd/go2tv/version.txt;then echo "GO2TV_VERSION=$(cat cmd/go2tv/version.txt)";else echo "GO2TV_VERSION=v$(cat cmd/go2tv/version.txt)";fi  >> $GITHUB_ENV

    - uses: WillAbides/setup-go-faster@v1.11.0
      id: setup-go-faster
      with:
        go-version: "*"

    - name: Get dependencies
      run: sudo apt update && sudo apt install xorg-dev

    - name: Package (Linux)
      run: GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o go2tv cmd/go2tv/go2tv.go
    
    - uses: actions/upload-artifact@v2
      with:
        name: go2tv_${{ env.GO2TV_VERSION }}_linux_amd64
        path: |
          LICENSE
          README.md
          go2tv
        retention-days: 2
